name: Mytest

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    permissions:
      actions: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Info
      run: echo "Start..."
    - name: TEST
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} > token.txt
